name: Metrics

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    # Runs every 4 hours
    - cron: "0 */4 * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          user: malahoffiw
          template: classic
          base: header
          base_hireable: yes
          config_timezone: Europe/Moscow
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_other: yes
          plugin_languages_sections: most-used
          plugin_languages_ignored: php
          plugin_leetcode: yes
          plugin_leetcode_sections: solved
          plugin_leetcode_user: .user.login
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}   
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: http://wakapi.dev
          plugin_wakatime_user: .user.login
