name: Waka Readme

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    # Runs every 4 hours
    - cron: "0 */4 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Waka - Readme
        uses: athul/waka-readme@v0.1.5
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TITLE: true
          TIME_RANGE: all_time
          SHOW_TIME: true
          
#       - uses: anmol098/waka-readme-stats@master
#         with:
#           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
#           GH_TOKEN: ${{ secrets.GH_TOKEN }}
#           SHOW_PROFILE_VIEWS: "False"
#           SHOW_SHORT_INFO: "False"
#           SHOW_LOC_CHART: "False"
